import React, { Component } from "react";
import WeatherItems from "./WeatherItems";

export default class Weather extends Component {
    response = {
        "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1655383731,
        "localtime": "2022-06-16 13:48"
        },
        "current": {
        "last_updated_epoch": 1655383500,
        "last_updated": "2022-06-16 13:45",
        "temp_c": 26,
        "temp_f": 78.8,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 250,
        "wind_dir": "WSW",
        "pressure_mb": 1022,
        "pressure_in": 30.18,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 34,
        "cloud": 0,
        "feelslike_c": 25.6,
        "feelslike_f": 78.2,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 7,
        "gust_mph": 7.2,
        "gust_kph": 11.5,
        "air_quality": {
        "co": 223.60000610351562,
        "no2": 15.100000381469727,
        "o3": 206,
        "so2": 22.200000762939453,
        "pm2_5": 25.100000381469727,
        "pm10": 27.600000381469727,
        "us-epa-index": 2,
        "gb-defra-index": 3
        }
        },
        "forecast": {
        "forecastday": [
        {
        "date": "2022-06-16",
        "date_epoch": 1655337600,
        "day": {
        "maxtemp_c": 30.8,
        "maxtemp_f": 87.4,
        "mintemp_c": 15.2,
        "mintemp_f": 59.4,
        "avgtemp_c": 22.5,
        "avgtemp_f": 72.5,
        "maxwind_mph": 9.4,
        "maxwind_kph": 15.1,
        "totalprecip_mm": 0,
        "totalprecip_in": 0,
        "avgvis_km": 10,
        "avgvis_miles": 6,
        "avghumidity": 52,
        "daily_will_it_rain": 0,
        "daily_chance_of_rain": 0,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "uv": 7
        },
        "astro": {
        "sunrise": "04:42 AM",
        "sunset": "09:20 PM",
        "moonrise": "11:59 PM",
        "moonset": "06:15 AM",
        "moon_phase": "Waxing Gibbous",
        "moon_illumination": "78"
        },
        "hour": [
        {
        "time_epoch": 1655334000,
        "time": "2022-06-16 00:00",
        "temp_c": 16.6,
        "temp_f": 61.9,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 28,
        "wind_dir": "NNE",
        "pressure_mb": 1020,
        "pressure_in": 30.11,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 69,
        "cloud": 11,
        "feelslike_c": 16.6,
        "feelslike_f": 61.9,
        "windchill_c": 16.6,
        "windchill_f": 61.9,
        "heatindex_c": 16.6,
        "heatindex_f": 61.9,
        "dewpoint_c": 10.8,
        "dewpoint_f": 51.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 5.1,
        "gust_kph": 8.3,
        "uv": 1
        },
        {
        "time_epoch": 1655337600,
        "time": "2022-06-16 01:00",
        "temp_c": 16,
        "temp_f": 60.8,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 1.6,
        "wind_kph": 2.5,
        "wind_degree": 19,
        "wind_dir": "NNE",
        "pressure_mb": 1020,
        "pressure_in": 30.11,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 71,
        "cloud": 0,
        "feelslike_c": 16,
        "feelslike_f": 60.8,
        "windchill_c": 16,
        "windchill_f": 60.8,
        "heatindex_c": 16,
        "heatindex_f": 60.8,
        "dewpoint_c": 10.7,
        "dewpoint_f": 51.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.7,
        "gust_kph": 4.3,
        "uv": 1
        },
        {
        "time_epoch": 1655341200,
        "time": "2022-06-16 02:00",
        "temp_c": 15.6,
        "temp_f": 60.1,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 2.5,
        "wind_kph": 4,
        "wind_degree": 357,
        "wind_dir": "N",
        "pressure_mb": 1020,
        "pressure_in": 30.13,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 72,
        "cloud": 3,
        "feelslike_c": 15.6,
        "feelslike_f": 60.1,
        "windchill_c": 15.6,
        "windchill_f": 60.1,
        "heatindex_c": 15.6,
        "heatindex_f": 60.1,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.5,
        "gust_kph": 7.2,
        "uv": 1
        },
        {
        "time_epoch": 1655344800,
        "time": "2022-06-16 03:00",
        "temp_c": 15.4,
        "temp_f": 59.7,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 1.3,
        "wind_kph": 2.2,
        "wind_degree": 10,
        "wind_dir": "N",
        "pressure_mb": 1020,
        "pressure_in": 30.12,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 74,
        "cloud": 3,
        "feelslike_c": 15.4,
        "feelslike_f": 59.7,
        "windchill_c": 15.4,
        "windchill_f": 59.7,
        "heatindex_c": 15.4,
        "heatindex_f": 59.7,
        "dewpoint_c": 10.7,
        "dewpoint_f": 51.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.5,
        "gust_kph": 4,
        "uv": 1
        },
        {
        "time_epoch": 1655348400,
        "time": "2022-06-16 04:00",
        "temp_c": 15.2,
        "temp_f": 59.4,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 0.9,
        "wind_kph": 1.4,
        "wind_degree": 354,
        "wind_dir": "N",
        "pressure_mb": 1020,
        "pressure_in": 30.13,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 74,
        "cloud": 4,
        "feelslike_c": 15.2,
        "feelslike_f": 59.4,
        "windchill_c": 15.2,
        "windchill_f": 59.4,
        "heatindex_c": 15.2,
        "heatindex_f": 59.4,
        "dewpoint_c": 10.6,
        "dewpoint_f": 51.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.6,
        "gust_kph": 2.5,
        "uv": 1
        },
        {
        "time_epoch": 1655352000,
        "time": "2022-06-16 05:00",
        "temp_c": 15.9,
        "temp_f": 60.6,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 0.7,
        "wind_kph": 1.1,
        "wind_degree": 302,
        "wind_dir": "WNW",
        "pressure_mb": 1021,
        "pressure_in": 30.14,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 71,
        "cloud": 8,
        "feelslike_c": 15.9,
        "feelslike_f": 60.6,
        "windchill_c": 15.9,
        "windchill_f": 60.6,
        "heatindex_c": 15.9,
        "heatindex_f": 60.6,
        "dewpoint_c": 10.6,
        "dewpoint_f": 51.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.1,
        "gust_kph": 1.8,
        "uv": 5
        },
        {
        "time_epoch": 1655355600,
        "time": "2022-06-16 06:00",
        "temp_c": 17.3,
        "temp_f": 63.1,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 1.6,
        "wind_kph": 2.5,
        "wind_degree": 280,
        "wind_dir": "W",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 64,
        "cloud": 6,
        "feelslike_c": 17.3,
        "feelslike_f": 63.1,
        "windchill_c": 17.3,
        "windchill_f": 63.1,
        "heatindex_c": 17.3,
        "heatindex_f": 63.1,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2,
        "gust_kph": 3.2,
        "uv": 5
        },
        {
        "time_epoch": 1655359200,
        "time": "2022-06-16 07:00",
        "temp_c": 19.5,
        "temp_f": 67.1,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 1.8,
        "wind_kph": 2.9,
        "wind_degree": 343,
        "wind_dir": "NNW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 56,
        "cloud": 6,
        "feelslike_c": 19.5,
        "feelslike_f": 67.1,
        "windchill_c": 19.5,
        "windchill_f": 67.1,
        "heatindex_c": 19.5,
        "heatindex_f": 67.1,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2,
        "gust_kph": 3.2,
        "uv": 5
        },
        {
        "time_epoch": 1655362800,
        "time": "2022-06-16 08:00",
        "temp_c": 21.6,
        "temp_f": 70.9,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 1.3,
        "wind_kph": 2.2,
        "wind_degree": 234,
        "wind_dir": "SW",
        "pressure_mb": 1022,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 49,
        "cloud": 4,
        "feelslike_c": 21.6,
        "feelslike_f": 70.9,
        "windchill_c": 21.6,
        "windchill_f": 70.9,
        "heatindex_c": 24.3,
        "heatindex_f": 75.7,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.6,
        "gust_kph": 2.5,
        "uv": 6
        },
        {
        "time_epoch": 1655366400,
        "time": "2022-06-16 09:00",
        "temp_c": 23.5,
        "temp_f": 74.3,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 3.1,
        "wind_kph": 5,
        "wind_degree": 210,
        "wind_dir": "SSW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 44,
        "cloud": 36,
        "feelslike_c": 24.7,
        "feelslike_f": 76.5,
        "windchill_c": 23.5,
        "windchill_f": 74.3,
        "heatindex_c": 24.7,
        "heatindex_f": 76.5,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 3.6,
        "gust_kph": 5.8,
        "uv": 6
        },
        {
        "time_epoch": 1655370000,
        "time": "2022-06-16 10:00",
        "temp_c": 24.5,
        "temp_f": 76.1,
        "is_day": 1,
        "condition": {
        "text": "Overcast",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
        "code": 1009
        },
        "wind_mph": 4,
        "wind_kph": 6.5,
        "wind_degree": 204,
        "wind_dir": "SSW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 41,
        "cloud": 100,
        "feelslike_c": 25.1,
        "feelslike_f": 77.2,
        "windchill_c": 24.5,
        "windchill_f": 76.1,
        "heatindex_c": 25.1,
        "heatindex_f": 77.2,
        "dewpoint_c": 10.5,
        "dewpoint_f": 50.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.7,
        "gust_kph": 7.6,
        "uv": 5
        },
        {
        "time_epoch": 1655373600,
        "time": "2022-06-16 11:00",
        "temp_c": 26.8,
        "temp_f": 80.2,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 5.6,
        "wind_kph": 9,
        "wind_degree": 207,
        "wind_dir": "SSW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 37,
        "cloud": 46,
        "feelslike_c": 26.5,
        "feelslike_f": 79.7,
        "windchill_c": 26.8,
        "windchill_f": 80.2,
        "heatindex_c": 26.5,
        "heatindex_f": 79.7,
        "dewpoint_c": 11,
        "dewpoint_f": 51.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.5,
        "gust_kph": 10.4,
        "uv": 7
        },
        {
        "time_epoch": 1655377200,
        "time": "2022-06-16 12:00",
        "temp_c": 29.7,
        "temp_f": 85.5,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 6.3,
        "wind_kph": 10.1,
        "wind_degree": 220,
        "wind_dir": "SW",
        "pressure_mb": 1022,
        "pressure_in": 30.17,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 34,
        "cloud": 4,
        "feelslike_c": 29,
        "feelslike_f": 84.2,
        "windchill_c": 29.7,
        "windchill_f": 85.5,
        "heatindex_c": 29,
        "heatindex_f": 84.2,
        "dewpoint_c": 12,
        "dewpoint_f": 53.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.2,
        "gust_kph": 11.5,
        "uv": 7
        },
        {
        "time_epoch": 1655380800,
        "time": "2022-06-16 13:00",
        "temp_c": 30.2,
        "temp_f": 86.4,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 5.8,
        "wind_kph": 9.4,
        "wind_degree": 213,
        "wind_dir": "SSW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 32,
        "cloud": 9,
        "feelslike_c": 29.3,
        "feelslike_f": 84.7,
        "windchill_c": 30.2,
        "windchill_f": 86.4,
        "heatindex_c": 29.3,
        "heatindex_f": 84.7,
        "dewpoint_c": 11.6,
        "dewpoint_f": 52.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.7,
        "gust_kph": 10.8,
        "uv": 8
        },
        {
        "time_epoch": 1655384400,
        "time": "2022-06-16 14:00",
        "temp_c": 30.2,
        "temp_f": 86.4,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 5.8,
        "wind_kph": 9.4,
        "wind_degree": 222,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.16,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 32,
        "cloud": 12,
        "feelslike_c": 29.4,
        "feelslike_f": 84.9,
        "windchill_c": 30.2,
        "windchill_f": 86.4,
        "heatindex_c": 29.4,
        "heatindex_f": 84.9,
        "dewpoint_c": 11.7,
        "dewpoint_f": 53.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.7,
        "gust_kph": 10.8,
        "uv": 8
        },
        {
        "time_epoch": 1655388000,
        "time": "2022-06-16 15:00",
        "temp_c": 30.8,
        "temp_f": 87.4,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 5.8,
        "wind_kph": 9.4,
        "wind_degree": 222,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.15,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 31,
        "cloud": 11,
        "feelslike_c": 29.9,
        "feelslike_f": 85.8,
        "windchill_c": 30.8,
        "windchill_f": 87.4,
        "heatindex_c": 29.9,
        "heatindex_f": 85.8,
        "dewpoint_c": 11.8,
        "dewpoint_f": 53.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.7,
        "gust_kph": 10.8,
        "uv": 8
        },
        {
        "time_epoch": 1655391600,
        "time": "2022-06-16 16:00",
        "temp_c": 30.8,
        "temp_f": 87.4,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 216,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.14,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 32,
        "cloud": 12,
        "feelslike_c": 30.1,
        "feelslike_f": 86.2,
        "windchill_c": 30.8,
        "windchill_f": 87.4,
        "heatindex_c": 30.1,
        "heatindex_f": 86.2,
        "dewpoint_c": 12.3,
        "dewpoint_f": 54.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 8
        },
        {
        "time_epoch": 1655395200,
        "time": "2022-06-16 17:00",
        "temp_c": 27.4,
        "temp_f": 81.3,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 9.2,
        "wind_kph": 14.8,
        "wind_degree": 219,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.14,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 37,
        "cloud": 14,
        "feelslike_c": 27,
        "feelslike_f": 80.6,
        "windchill_c": 27.4,
        "windchill_f": 81.3,
        "heatindex_c": 27,
        "heatindex_f": 80.6,
        "dewpoint_c": 11.4,
        "dewpoint_f": 52.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.5,
        "gust_kph": 16.9,
        "uv": 7
        },
        {
        "time_epoch": 1655398800,
        "time": "2022-06-16 18:00",
        "temp_c": 25.7,
        "temp_f": 78.3,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 214,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.14,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 43,
        "cloud": 10,
        "feelslike_c": 26,
        "feelslike_f": 78.8,
        "windchill_c": 25.7,
        "windchill_f": 78.3,
        "heatindex_c": 26,
        "heatindex_f": 78.8,
        "dewpoint_c": 12.2,
        "dewpoint_f": 54,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.7,
        "gust_kph": 17.3,
        "uv": 7
        },
        {
        "time_epoch": 1655402400,
        "time": "2022-06-16 19:00",
        "temp_c": 24.6,
        "temp_f": 76.3,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 214,
        "wind_dir": "SW",
        "pressure_mb": 1021,
        "pressure_in": 30.15,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 49,
        "cloud": 10,
        "feelslike_c": 25.5,
        "feelslike_f": 77.9,
        "windchill_c": 24.6,
        "windchill_f": 76.3,
        "heatindex_c": 25.5,
        "heatindex_f": 77.9,
        "dewpoint_c": 13.2,
        "dewpoint_f": 55.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.7,
        "gust_kph": 14,
        "uv": 6
        },
        {
        "time_epoch": 1655406000,
        "time": "2022-06-16 20:00",
        "temp_c": 22.1,
        "temp_f": 71.8,
        "is_day": 1,
        "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
        },
        "wind_mph": 5.1,
        "wind_kph": 8.3,
        "wind_degree": 223,
        "wind_dir": "SW",
        "pressure_mb": 1022,
        "pressure_in": 30.17,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 55,
        "cloud": 8,
        "feelslike_c": 24.6,
        "feelslike_f": 76.3,
        "windchill_c": 22.1,
        "windchill_f": 71.8,
        "heatindex_c": 24.6,
        "heatindex_f": 76.3,
        "dewpoint_c": 12.8,
        "dewpoint_f": 55,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.4,
        "gust_kph": 11.9,
        "uv": 6
        },
        {
        "time_epoch": 1655409600,
        "time": "2022-06-16 21:00",
        "temp_c": 20.7,
        "temp_f": 69.3,
        "is_day": 1,
        "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
        },
        "wind_mph": 3.6,
        "wind_kph": 5.8,
        "wind_degree": 200,
        "wind_dir": "SSW",
        "pressure_mb": 1022,
        "pressure_in": 30.17,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 60,
        "cloud": 44,
        "feelslike_c": 20.7,
        "feelslike_f": 69.3,
        "windchill_c": 20.7,
        "windchill_f": 69.3,
        "heatindex_c": 20.7,
        "heatindex_f": 69.3,
        "dewpoint_c": 12.8,
        "dewpoint_f": 55,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 5.6,
        "gust_kph": 9,
        "uv": 6
        },
        {
        "time_epoch": 1655413200,
        "time": "2022-06-16 22:00",
        "temp_c": 20.2,
        "temp_f": 68.4,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 208,
        "wind_dir": "SSW",
        "pressure_mb": 1022,
        "pressure_in": 30.18,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 61,
        "cloud": 20,
        "feelslike_c": 20.2,
        "feelslike_f": 68.4,
        "windchill_c": 20.2,
        "windchill_f": 68.4,
        "heatindex_c": 20.2,
        "heatindex_f": 68.4,
        "dewpoint_c": 12.5,
        "dewpoint_f": 54.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.5,
        "gust_kph": 7.2,
        "uv": 1
        },
        {
        "time_epoch": 1655416800,
        "time": "2022-06-16 23:00",
        "temp_c": 19.5,
        "temp_f": 67.1,
        "is_day": 0,
        "condition": {
        "text": "Clear",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
        "code": 1000
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 215,
        "wind_dir": "SW",
        "pressure_mb": 1022,
        "pressure_in": 30.18,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 63,
        "cloud": 11,
        "feelslike_c": 19.5,
        "feelslike_f": 67.1,
        "windchill_c": 19.5,
        "windchill_f": 67.1,
        "heatindex_c": 19.5,
        "heatindex_f": 67.1,
        "dewpoint_c": 12.3,
        "dewpoint_f": 54.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.7,
        "gust_kph": 7.6,
        "uv": 1
        }
        ]
        }
        ]
        },
        "alerts": {
        "alert": []
        }
        }
        
  constructor() {
    super();
    this.state = {
      response: this.response,
    };
  }
  render() {
    return (
      <div className="container">
        <div>
          <WeatherItems
            location={this.response.location.name}
            country={this.response.location.country}
            windSpeed={this.response.current.wind_kph}
            temperature={this.response.current.temp_c}
            skyCondition={this.response.current.condition.text}
            imageUrl={this.response.current.condition.icon}
            cloud={this.response.current.cloud}
            pressure={this.response.current.pressure_mb}
            time={this.response.location.localtime}
            Fsunrise = {this.response.forecast.forecastday[0].astro.sunrise}
            FsunSet = {this.response.forecast.forecastday[0].astro.sunset}
            FmoonRise = {this.response.forecast.forecastday[0].astro.moonrise}
            FmoonSet = {this.response.forecast.forecastday[0].astro.moonset}
            
            FmaxTemperature = {this.response.forecast.forecastday[0].day.maxtemp_c}
            FminTemperature = {this.response.forecast.forecastday[0].day.mintemp_c}
            FmaxWindSpeed = {this.response.forecast.forecastday[0].day.maxwind_kph}          
            rain = {this.response.forecast.forecastday[0].day.daily_chance_of_rain}
            snow = {this.response.forecast.forecastday[0].day.daily_chance_of_snow}
            FimageUrl = {this.response.forecast.forecastday[0].day.condition.icon}
            FskyCondition = {this.response.forecast.forecastday[0].day.condition.text}

          />
        </div>
      </div>
    );
  }
}
